[2023-04-04T18:07:40.234+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_final_project.run_dbt_task manual__2023-04-04T18:07:00.147143+00:00 [queued]>
[2023-04-04T18:07:40.256+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_final_project.run_dbt_task manual__2023-04-04T18:07:00.147143+00:00 [queued]>
[2023-04-04T18:07:40.257+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T18:07:40.258+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-04-04T18:07:40.258+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T18:07:40.284+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): run_dbt_task> on 2023-04-04 18:07:00.147143+00:00
[2023-04-04T18:07:40.304+0000] {standard_task_runner.py:55} INFO - Started process 215 to run task
[2023-04-04T18:07:40.315+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_final_project', 'run_dbt_task', 'manual__2023-04-04T18:07:00.147143+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_final_project.py', '--cfg-path', '/tmp/tmptxb7n0i5']
[2023-04-04T18:07:40.320+0000] {standard_task_runner.py:83} INFO - Job 47: Subtask run_dbt_task
[2023-04-04T18:07:40.489+0000] {task_command.py:376} INFO - Running <TaskInstance: data_ingestion_final_project.run_dbt_task manual__2023-04-04T18:07:00.147143+00:00 [running]> on host de0aa116b028
[2023-04-04T18:07:40.626+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_final_project
AIRFLOW_CTX_TASK_ID=run_dbt_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T18:07:00.147143+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-04T18:07:00.147143+00:00
[2023-04-04T18:07:40.630+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-04T18:07:40.631+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --profiles-dir /home/febi99/.dbt/profiles.yml']
[2023-04-04T18:07:40.664+0000] {subprocess.py:86} INFO - Output:
[2023-04-04T18:07:50.718+0000] {subprocess.py:93} INFO - [0m18:07:50  Encountered an error:
[2023-04-04T18:07:50.719+0000] {subprocess.py:93} INFO - Runtime Error
[2023-04-04T18:07:50.719+0000] {subprocess.py:93} INFO -   fatal: Not a dbt project (or any of the parent directories). Missing dbt_project.yml file
[2023-04-04T18:07:51.649+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-04T18:07:51.679+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-04T18:07:51.691+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_final_project, task_id=run_dbt_task, execution_date=20230404T180700, start_date=20230404T180740, end_date=20230404T180751
[2023-04-04T18:07:51.757+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 47 for task run_dbt_task (Bash command failed. The command returned a non-zero exit code 2.; 215)
[2023-04-04T18:07:51.811+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-04-04T18:07:51.882+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
