[2023-04-04T18:25:47.397+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_final_project.run_dbt_task manual__2023-04-04T18:25:08.427422+00:00 [queued]>
[2023-04-04T18:25:47.427+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_final_project.run_dbt_task manual__2023-04-04T18:25:08.427422+00:00 [queued]>
[2023-04-04T18:25:47.428+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T18:25:47.429+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-04-04T18:25:47.430+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T18:25:47.474+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): run_dbt_task> on 2023-04-04 18:25:08.427422+00:00
[2023-04-04T18:25:47.495+0000] {standard_task_runner.py:55} INFO - Started process 175 to run task
[2023-04-04T18:25:47.513+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_final_project', 'run_dbt_task', 'manual__2023-04-04T18:25:08.427422+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_final_project.py', '--cfg-path', '/tmp/tmpibr87dqb']
[2023-04-04T18:25:47.519+0000] {standard_task_runner.py:83} INFO - Job 55: Subtask run_dbt_task
[2023-04-04T18:25:47.792+0000] {task_command.py:376} INFO - Running <TaskInstance: data_ingestion_final_project.run_dbt_task manual__2023-04-04T18:25:08.427422+00:00 [running]> on host 76d23bd3ee71
[2023-04-04T18:25:48.286+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_final_project
AIRFLOW_CTX_TASK_ID=run_dbt_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T18:25:08.427422+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-04T18:25:08.427422+00:00
[2023-04-04T18:25:48.289+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-04T18:25:48.299+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/bank_marketing_dwh && dbt run --project-dir /opt/***/bank_marketing_dwh --models staging dwh']
[2023-04-04T18:25:48.380+0000] {subprocess.py:86} INFO - Output:
[2023-04-04T18:25:56.582+0000] {subprocess.py:93} INFO - [0m18:25:56  Encountered an error while reading the project:  ERROR: Runtime Error
[2023-04-04T18:25:56.583+0000] {subprocess.py:93} INFO -   Could not find profile named 'bank_marketing_dwh'
[2023-04-04T18:25:56.614+0000] {subprocess.py:93} INFO - [0m18:25:56  Encountered an error:
[2023-04-04T18:25:56.615+0000] {subprocess.py:93} INFO - Runtime Error
[2023-04-04T18:25:56.616+0000] {subprocess.py:93} INFO -   Could not run dbt
[2023-04-04T18:25:57.142+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-04T18:25:57.180+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-04T18:25:57.196+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_final_project, task_id=run_dbt_task, execution_date=20230404T182508, start_date=20230404T182547, end_date=20230404T182557
[2023-04-04T18:25:57.253+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 55 for task run_dbt_task (Bash command failed. The command returned a non-zero exit code 2.; 175)
[2023-04-04T18:25:57.305+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-04-04T18:25:57.353+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
